export const GENRES = [
    "Fiction",
    "Drama",
    "Romance",
    "Classic",
    "Literary",
    "Science",
    "History",
    "Biography",
    "Fantasy",
    "Horror",
    "Mystery",
    "Thriller",
    "Adventure",
    "Poetry",
    "Philosophy",
    "Self-Help",
    "Travel",
    "Children",
    "Young Adult",
    "Science Fiction",
    "Satire",
    "Memoir",
    "Crime",
    "Graphic Novel",
    "Religion",
];
